### ISSUE TITLE
Losing inner stream of `TimeoutStream` on timeout with into_future

### ISSUE THREAD

**Issue by jonhoo** [tokio-rs/tokio-timer#10]
I have a `futures::sync::mpsc::Receiver`, and want to read a single value from it *with a timeout*. Crucially though, I don't *always* want the stream to have a timeout, so I want to recover the original stream after the read. However, I can't seem to find a way to do this correctly. Consider the code below:

```rust
use futures::{Future, Sink, Stream};
use tokio_timer::Timer;

const SEND_DELAY: u64 = 10;
const TIMEOUT: u64 = 1000;

fn main() {
    use std::time;
    use std::thread;
    let (tx, mut rx) = futures::sync::mpsc::channel(1);

    thread::spawn(move || {
        thread::sleep(time::Duration::from_millis(SEND_DELAY));
        tx.send("hello").wait().is_ok();
    });

    let timed_ch = Timer::default().timeout_stream(rx, time::Duration::from_millis(TIMEOUT));
    let next = match timed_ch.into_future().wait() {
        Ok((next, ch)) => {
            rx = ch.into_inner();
            Ok(next)
        }
        Err((err, ch)) => {
            rx = ch.into_inner();
            Err(err)
        }
    };
    drop(rx);

    println!("{:?}", next);
}
```

This code works just fine. But try changing `SEND_DELAY` and `TIMEOUT` such that `TIMEOUT < SEND_DELAY`. You'll see the code fail with
```
thread 'main' panicked at 'the stream has already been consumed'
```
This is because the call to `ch.into_inner()` in the `Err` case fails, as the stream was already taken when the timeout expired [here](https://github.com/tokio-rs/tokio-timer/blob/master/src/timer.rs#L390). That code returns the stream in a [`TimeoutError::TimedOut`](https://github.com/tokio-rs/tokio-timer/blob/master/src/timer.rs#L391), but the type of `err` in the code above is inexplicably `()`, which means the original stream is entirely lost.

What am I missing here? How can I recover the stream when using `into_future`?

**Comment by jonhoo** [comment]
After some pointers by @carllerche, it seems like this requires the same hack as @alexcrichton proposed in https://github.com/alexcrichton/futures-rs/issues/401#issuecomment-284443916, namely:
```rust
let mut rx = rx.map_err(|_| unreachable!());
```

Then, the code can be changed to 
```rust
// ...
let mut rx = rx.map_err(|_| unreachable!());
let timed_ch = Timer::default().timeout_stream(rx, time::Duration::from_millis(TIMEOUT));
let next = match timed_ch.wait().into_future() {
    Ok((next, ch)) => {
        rx = ch.into_inner();
        Ok(next)
    }
    Err((err, _)) => {
        let ch = match err {
            TimeoutError::TimedOut(ch) => ch,
            TimeoutError::Timer(ch, _) => ch,
        };
        rx = ch;
        Err(())
    }
};
```

I don't know what the right response to this is... Getting rid of the `From` that "automagically" [turns `Time*Error` into `()`](https://github.com/tokio-rs/tokio-timer/blob/f80e1de8c87d2a96cd8b6122329897f52545e78c/src/timer.rs#L467) would be a start, as that would turn this into a compile-time error. The other thing would be to modify `mpsc::Receiver` such that its `Stream::Error` is generic. I honestly don't know.. :/

**Comment by carllerche** [comment]
My take is that it is more common to just want to drop the `Stream` on timeout vs. trying to retrieve it. This was the original reason for the conversion, as not having it would add much more boilerplate for the common case.

Given that, I'm going to opt to leave it for now.

**Comment by 46bit** [comment]
Would you be willing to have an additional timeout mechanism that does allow recovering the stream? I built https://github.com/sirpent-team/tokio-timer/commit/e8ccbc16 to do this, as while a potentially less common case it seems far from unique.

**Comment by carllerche** [comment]
@46bit I'm not sure what the actionable steps are. Could you open a new issue if there is something else that needs to be done?

Also, `MapErr` should have `into_inner`, so if it is lacking, I would open an issue on the futures-rs repo or submit a PR.
