### ISSUE TITLE
Add a convenience function for timing out a given future

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio-timer#3]
`timer.timeout<F>(future: F, when: Instant) -> Expire<F, ?>`

Relates to tokio-rs/tokio-core#11

**Comment by ryandbair** [comment]
Looks like this is currently implemented:
https://github.com/tokio-rs/tokio-timer/blob/4acaed628ec796350490fe36ed16169a3bb1e143/src/timer.rs#L75

**Comment by carllerche** [comment]
Yep. Thanks :)
