### ISSUE TITLE
Should use `ptr::write`

### ISSUE THREAD

**Issue by stjepang** [tokio-rs/tokio-timer#31]
I've seen this mistake in multiple implementations of Dmitry Vyukov's MPMC queue in Rust.
In `mpmc.rs`:

```rust
(*node.get()).value = Some(value);
```

This is okay if `value` is `Copy`, but looks like `T` doesn't necessarily implement `Copy`:

```rust
impl<T: Send, U: Send + Copy> Queue<T, U> {
```

The problem is that writing the new value like this implies that the old value is dropped. In other words, a destructor will be run for a potentially non-existent value in memory. This is unsafe!

The correct way to write the value would be:

```rust
ptr::write(&mut (*node.get()).value, Some(value));
```

**Comment by stjepang** [comment]
Interestingly, the MPMC queue from Rust's pre-1.0 stdlib is broken in the same way:

https://docs.rs/mpmc/0.1.2/src/mpmc/lib.rs.html#113

You might have the same error in other crates where you reimplemented this queue, so I advise checking those implementations as well. :)

**Comment by carllerche** [comment]
It's been a while since I looked at the mpmc code, but I believe:

1) the current value is `None`
2) The ownership of the slot has been acquired above

So, there is nothing wrong w/ dropping

**Comment by stjepang** [comment]
Oh, I see. The value being `None` solves the problem.

Sorry for the non-bug report! :) Closing.
