### ISSUE TITLE
0.2.0 has been published from another repo? on crates.io and broke APIs ...

### ISSUE THREAD

**Issue by przygienda** [tokio-rs/tokio-timer#42]
Where is 0.2.0 on crates.io coming from? It broke APIs (TimeoutError imports) ?

**Comment by carllerche** [comment]
It's here: https://github.com/tokio-rs/tokio/tree/master/tokio-timer

0.1 -> 0.2 is a breaking release. It shouldn't be too hard to update.

**Comment by przygienda** [comment]
yes, you are correct ... 0.2 is breaking as indicated by numbering ...
