### ISSUE TITLE
The max_timeout check can panic

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio-timer#5]
https://github.com/tokio-rs/tokio-timer/blob/master/src/timer.rs#L132

**Comment by ryandbair** [comment]
Guessing this is referring to the usage at https://github.com/tokio-rs/tokio-timer/blob/4acaed628ec796350490fe36ed16169a3bb1e143/src/timer.rs#L143

How can this panic?

**Comment by carllerche** [comment]
I think this was fixed :) Closing for now.
