### ISSUE TITLE
Anticipating message from a Stream

### ISSUE THREAD

**Issue by 46bit** [tokio-rs/tokio-timer#8]
I have a suggestion for the library, to ease reading from streams with a timeout. A `Timer::anticipate` method will take a `Stream` and a `Duration`, returning a future.

* Ok: If a stream item arrives within the timeout it will emit the item and the stream for later use.
* Err: If the timeout passes without a message it will return a TimeoutError and the stream for later use.

`StreamFuture::Error = (S::Error, S)` does return the stream if there's an error. Wrapping this with `Timer::timeout` requires conversion of `TimeoutError` into `(S::Error, S)`. That's not natural and forces discarding the stream if the timeout passes. In this usecase a timeout shouldn't be an error: we may want to still use the stream later.

I'm not entirely sure what to do about a stream closing (`Async::Ready(None)`). `StreamFuture` does `Ok(Async::Ready(None, stream))` but this would make the stream closing and the timeout being reached indistinguishable. My implementation converts stream closed into a `TimeoutError::StreamClosed` for now.

Given the ephemerality of the chatroom I wasn't sure where best to discuss this besides a full issue.

**Comment by carllerche** [comment]
Hey, I made a bunch of changes. Does `Timer::timeout_stream` satisfy your needs?

I also changed `TimeoutError` to include the underlying future / stream, so you shouldn't be forced to lose it if the timeout is hit.

**Comment by 46bit** [comment]
That looks lovely. I considered such a timeouting stream but was concerned it would be implementing a stream which gets one message each duration rather than something more flexible. But it looks like I can `into_inner` when no longer anticipating a message then reconstruct a `TimeoutStream` when I am again? I think I've learned something about design here.

**Comment by carllerche** [comment]
Yep, exactly. I'll close this issue for now. Feel free to open another later.
